# Generated by Django 4.0.2 on 2022-02-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('closed', 'بسته شده')], default='pending', max_length=100, verbose_name='وضعیت'),
        ),
    ]
